sudo: required
services:
  - docker

before_install:
  - docker build -t tomastoews/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tomastoews/docker-react npm run test -- --coverage

    # language: generic 
